const data = [
    {country:  "AF", value: "اینجا چه اتفاقی افتاد"},
    {country:  "AX", value: "vad hände här"},
    {country:  "AL", value: "çfare ndodhi ketu"},
    {country:  "DZ", value: "ماذا حدث هنا؟"},
    {country:  "AS", value: "o le a le mea na tupu iinei?"},
    {country:  "AD", value: "què ha passat aquí?"},
    {country:  "AO", value: "o que aconteceu aqui?"},
    {country:  "AI", value: "what happened here?"},
    {country:  "AQ", value: "what happened here?"},
    {country:  "AG", value: "what happened here?"},
    {country:  "AR", value: "¿que pasó aquí?"},
    {country:  "AM", value: "ինչ է տեղի ունեցել այստեղ"},
    {country:  "AW", value: "wat is hier gebeurd?"},
    {country:  "AU", value: "what happened here?"},
    {country:  "AT", value: "was ist hier passiert?"},
    {country:  "AZ", value: "burda ne olub?"},
    {country:  "BS", value: "what happened here?"},
    {country:  "BH", value: "ماذا حدث هنا؟"},
    {country:  "BD", value: "সেখানে কি ঘটেছিল?"},
    {country:  "BB", value: "what happened here?"},
    {country:  "BY", value: "што тут здарылася?"},
    {country:  "BE", value: "wat is hier gebeurd?"},
    {country:  "BZ", value: "what happened here?"},
    {country:  "BJ", value: "que s'est-il passé ici?"},
    {country:  "BM", value: "what happened here?"},
    {country:  "BT", value: "འོག་གི་དུས་གསུང་གིས་ལ་བསྐྱོད་པའི་ཁྱེད་མ་ཚུགས་པ་དང་ནང་ལ་བསྐྱོད་པའི་ཁྱེད་མ་ལས་རྫོགས་པའི་དུས་འཚོལ་པ་བཟོ་བའི་རྩོམ་པ།"},
    {country:  "BO", value: "¿que pasó aquí?"},
    {country:  "BA", value: "šta se desilo ovde?"},
    {country:  "BW", value: "what happened here?"},
    {country:  "BV", value: "hva skjedde her?"},
    {country:  "BR", value: "o que aconteceu aqui?"},
    {country:  "IO", value: "what happened here?"},
    {country:  "BN", value: "apa yang berlaku di sini?"},
    {country:  "BG", value: "Какво е станало тук?"},
    {country:  "BF", value: "que s'est-il passé ici?"},
    {country:  "BI", value: "Vyagenze gute hano?"},
    {country:  "KH", value: "តើមានអ្វីកើតឡើងនៅទីនេះ?"},
    {country:  "CM", value: "que s'est-il passé ici?"},
    {country:  "CA", value: "what happened here?"},
    {country:  "CV", value: "o que aconteceu aqui?"},
    {country:  "KY", value: "what happened here?"},
    {country:  "CF", value: "que s'est-il passé ici?"},
    {country:  "TD", value: "que s'est-il passé ici?"},
    {country:  "CL", value: "¿Que pasó aquí?"},
    {country:  "CN", value: "这里发生了什么？"},
    {country:  "CX", value: "what happened here?"},
    {country:  "CC", value: "apa yang berlaku di sini?"},
    {country:  "CO", value: "¿Que pasó aquí?"},
    {country:  "KM", value: "que s'est-il passé ici?"},
    {country:  "CG", value: "que s'est-il passé ici?"},
    {country:  "CD", value: "que s'est-il passé ici?"},
    {country:  "CK", value: "what happened here?"},
    {country:  "CR", value: "¿Que pasó aquí?"},
    {country:  "CI", value: "que s'est-il passé ici?"},

    
    {country:  "HR", value: "Croatia"},
    {country:  "CU", value: "Cuba"},
    {country:  "CY", value: "Cyprus"},
    {country:  "CZ", value: "Czech Republic"},
    {country:  "DK", value: "Denmark"},
    {country:  "DJ", value: "Djibouti"},
    {country:  "DM", value: "what happened here?"},
    {country:  "DO", value: "¿Que pasó aquí?"},
    {country:  "EC", value: "Ecuador"},
    {country:  "EG", value: "ماذا حدث هنا؟"},
    {country:  "SV", value: "El Salvador"},
    {country:  "GQ", value: "Equatorial Guinea"},
    {country:  "ER", value: "Eritrea"},
    {country:  "EE", value: "Estonia"},
    {country:  "ET", value: "Ethiopia"},
    {country:  "FK", value: "Falkland Islands (Malvinas)"},
    {country:  "FO", value: "Faroe Islands"},
    {country:  "FJ", value: "na cava a yaco eke?"},
    {country:  "FI", value: "Finland"},
    {country:  "FR", value: "que s'est-il passé ici?"},
    {country:  "GF", value: "French Guiana"},
    {country:  "PF", value: "French Polynesia"},
    {country:  "TF", value: "French Southern Territories"},
    {country:  "GA", value: "que s'est-il passé ici?"},
    {country:  "GM", value: "Gambia"},
    {country:  "GE", value: "Georgia"},
    {country:  "DE", value: "Germany"},
    {country:  "GH", value: "Ghana"},
    {country:  "GI", value: "Gibraltar"},
    {country:  "GR", value: "τι συνέβη εδώ?"},
    {country:  "GL", value: "suna maani piva?"},
    {country:  "GD", value: "Grenada"},
    {country:  "GP", value: "Guadeloupe"},
    {country:  "GU", value: "sa' håyi nayinifiha i masinahon?"},
    {country:  "GT", value: "¿que pasó aquí?"},
    {country:  "GG", value: "Guernsey"},
    {country:  "GN", value: "que s'est-il passé ici?"},
    {country:  "GW", value: "o que aconteceu aqui?"},
    {country:  "GY", value: "Guyana"},
    {country:  "HT", value: "Haiti"},
    {country:  "HM", value: "Heard Island & Mcdonald Islands"},
    {country:  "VA", value: "Holy See (Vatican City State)"},
    {country:  "HN", value: "Honduras"},
    {country:  "HK", value: "Hong Kong"},
    {country:  "HU", value: "Hungary"},
    {country:  "IS", value: "Iceland"},
    {country:  "IN", value: "India"},
    {country:  "ID", value: "Indonesia"},
    {country:  "IR", value: "Iran, Islamic Republic Of"},
    {country:  "IQ", value: "ماذا حدث هنا؟"},
    {country:  "IE", value: "Ireland"},
    {country:  "IM", value: "Isle Of Man"},
    {country:  "IL", value: "Israel"},
    {country:  "IT", value: "Italy"},
    {country:  "JM", value: "Jamaica"},
    {country:  "JP", value: "Japan"},
    {country:  "JE", value: "Jersey"},
    {country:  "JO", value: "ماذا حدث هنا؟"},
    {country:  "KZ", value: "что здесь случилось?"},
    {country:  "KE", value: "nini kilitokea hapa?"},
    {country:  "KI", value: "Kiribati"},
    {country:  "KR", value: "Korea"},
    {country:  "KP", value: "North Korea"},
    {country:  "KW", value: "ماذا حدث هنا؟"},
    {country:  "KG", value: "что здесь случилось?"},
    {country:  "LA", value: "Lao People\"s Democratic Republic"},
    {country:  "LV", value: "Latvia"},
    {country:  "LB", value: "ماذا حدث هنا؟"},
    {country:  "LS", value: "Lesotho"},
    {country:  "LR", value: "Liberia"},
    {country:  "LY", value: "ماذا حدث هنا؟"},
    {country:  "LI", value: "Liechtenstein"},
    {country:  "LT", value: "Lithuania"},
    {country:  "LU", value: "Luxembourg"},
    {country:  "MO", value: "o que aconteceu aqui?"},
    {country:  "MK", value: "Macedonia"},
    {country:  "MG", value: "Madagascar"},
    {country:  "MW", value: "Malawi"},
    {country:  "MY", value: "Malaysia"},
    {country:  "MV", value: "Maldives"},
    {country:  "ML", value: "Mali"},
    {country:  "MT", value: "Malta"},
    {country:  "MH", value: "Marshall Islands"},
    {country:  "MQ", value: "Martinique"},
    {country:  "MR", value: "ماذا حدث هنا؟"},
    {country:  "MU", value: "Mauritius"},
    {country:  "YT", value: "Mayotte"},
    {country:  "MX", value: "¿que pasó aquí?"},
    {country:  "FM", value: "Micronesia, Federated States Of"},
    {country:  "MD", value: "Moldova"},
    {country:  "MC", value: "que s'est-il passé ici?"},
    {country:  "MN", value: "Mongolia"},
    {country:  "ME", value: "Montenegro"},
    {country:  "MS", value: "Montserrat"},
    {country:  "MA", value: "Morocco"},
    {country:  "MZ", value: "o que aconteceu aqui?"},
    {country:  "MM", value: "Myanmar"},
    {country:  "NA", value: "Namibia"},
    {country:  "NR", value: "Nauru"},
    {country:  "NP", value: "Nepal"},
    {country:  "NL", value: "Netherlands"},
    {country:  "AN", value: "Netherlands Antilles"},
    {country:  "NC", value: "New Caledonia"},
    {country:  "NZ", value: "i aha i konei?"},
    {country:  "NI", value: "Nicaragua"},
    {country:  "NE", value: "que s'est-il passé ici?"},
    {country:  "NG", value: "Nigeria"},
    {country:  "NU", value: "Niue"},
    {country:  "NF", value: "Norfolk Island"},
    {country:  "MP", value: "Northern Mariana Islands"},
    {country:  "NO", value: "hva skjedde her?"},
    {country:  "OM", value: "ماذا حدث هنا؟"},
    {country:  "PK", value: "Pakistan"},
    {country:  "PW", value: "Palau"},
    {country:  "PS", value: "ماذا حدث هنا؟"},
    {country:  "PA", value: "¿que pasó aquí?"},
    {country:  "PG", value: "Wanem samting i bin kamap long hia?"},
    {country:  "PY", value: "mba’épa oiko ko’ápe?"},
    {country:  "PE", value: "¿que pasó aquí?"},
    {country:  "PH", value: "anong nangyari dito?"},
    {country:  "PN", value: "Pitcairn"},
    {country:  "PL", value: "Poland"},
    {country:  "PT", value: "o que aconteceu aqui?"},
    {country:  "PR", value: "¿que pasó aquí?"},
    {country:  "QA", value: "ماذا حدث هنا؟"},
    {country:  "RE", value: "Reunion"},
    {country:  "RO", value: "Romania"},
    {country:  "RU", value: "что здесь случилось?"},
    {country:  "RW", value: "Rwanda"},
    {country:  "BL", value: "que s'est-il passé ici?"},
    {country:  "SH", value: "what happened here?"},
    {country:  "KN", value: "Saint Kitts And Nevis"},
    {country:  "LC", value: "Saint Lucia"},
    {country:  "MF", value: "Saint Martin"},
    {country:  "PM", value: "Saint Pierre And Miquelon"},
    {country:  "VC", value: "Saint Vincent And Grenadines"},
    {country:  "WS", value: "Samoa"},
    {country:  "SM", value: "San Marino"},
    {country:  "ST", value: "o que aconteceu aqui?"},
    {country:  "SA", value: "ماذا حدث هنا؟"},
    {country:  "SN", value: "que s'est-il passé ici?"},
    {country:  "RS", value: "Serbia"},
    {country:  "SC", value: "Seychelles"},
    {country:  "SL", value: "Sierra Leone"},
    {country:  "SG", value: "这里发生了什么？"},
    {country:  "SK", value: "Slovakia"},
    {country:  "SI", value: "Slovenia"},
    {country:  "SB", value: "Solomon Islands"},
    {country:  "SO", value: "maxaa ka dhacay halkan?"},
    {country:  "ZA", value: "kwenzekeni lapha?"},
    {country:  "GS", value: "what happened here?"},
    {country:  "ES", value: "¿que pasó aquí?"},
    {country:  "LK", value: "මෙහි සිදු වූ දේ?"},
    {country:  "SD", value: "ماذا حدث هنا؟"},
    {country:  "SR", value: "Suriname"},
    {country:  "SJ", value: "Svalbard And Jan Mayen"},
    {country:  "SZ", value: "Swaziland"},
    {country:  "SE", value: "Sweden"},
    {country:  "CH", value: "Switzerland"},
    {country:  "SY", value: "ماذا حدث هنا؟"},
    {country:  "TW", value: "这里发生了什么？"},
    {country:  "TJ", value: "Tajikistan"},
    {country:  "TZ", value: "nini kilitokea hapa?"},
    {country:  "TH", value: "Thailand"},
    {country:  "TL", value: "o que aconteceu aqui?"},
    {country:  "TG", value: "que s'est-il passé ici?"},
    {country:  "TK", value: "Tokelau"},
    {country:  "TO", value: "Tonga"},
    {country:  "TT", value: "Trinidad And Tobago"},
    {country:  "TN", value: "ماذا حدث هنا؟"},
    {country:  "TR", value: "Turkey"},
    {country:  "TM", value: "Turkmenistan"},
    {country:  "TC", value: "Turks And Caicos Islands"},
    {country:  "TV", value: "Tuvalu"},
    {country:  "UG", value: "nini kilitokea hapa?"},
    {country:  "UA", value: "Ukraine"},
    {country:  "AE", value: "ماذا حدث هنا؟"},
    {country:  "GB", value: "what happened here?"},
    {country:  "US", value: "what happened here?"},
    {country:  "UM", value: "what happened here?"},
    {country:  "UY", value: "Uruguay"},
    {country:  "UZ", value: "Uzbekistan"},
    {country:  "VU", value: "Vanuatu"},
    {country:  "VE", value: "¿que pasó aquí?"},
    {country:  "VN", value: "Vietnam"},
    {country:  "VG", value: "Virgin Islands, British"},
    {country:  "VI", value: "Virgin Islands, U.S."},
    {country:  "WF", value: "Wallis And Futuna"},
    {country:  "EH", value: "Western Sahara"},
    {country:  "YE", value: "ماذا حدث هنا؟"},
    {country:  "ZM", value: "Zambia"},
    {country:  "ZW", value: "Zimbabwe"}
];
export default data;
